# On part d'une image de base alpine avec NODE v20
FROM node:20-alpine
# Définit le dossier de travail dans le conteneur
WORKDIR /app
# Copie les fichiers du projet dans le conteneur
COPY . .
# Copie les fichiers du projet dans le conteneur
CMD ["node", "app.js"]