# Choisir une image de base avec Node.js
FROM node:20-alpine
# Définit le dossier de travail dans le conteneur
WORKDIR /app
# Copie les fichiers du projet dans le conteneur
COPY . .
# Copie les fichiers du projet dans le conteneur
CMD ["node", "app.js"]