version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    

  redis:
    image: redis:7-alpine
    volumes: 
      - redis-data:/data

volumes:
  redis-data: