services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trainingdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: trainer@example.com
      PGADMIN_DEFAULT_PASSWORD: secret123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: